# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Automated Tests

on:
  push:
    branches:
      - '*'
      - '!gui_implimentation'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven      
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots -DCF_ACCESS_CLIENT_ID="${{vars.CF_ACCESS_CLIENT_ID}}" -DCF_ACCESS_CLIENT_SECRET="${{vars.CF_ACCESS_CLIENT_SECRET}}" -DCLIENT_SECRET="${{vars.CLIENT_SECRET}}" package --file pom.xml
